let photoPosts = [
	{ 
		id: '1',
		description: 'Hey guys! <br /> Here you can se me preparing to make love to this beautiful can of "Baltika7" beer after a long day in university. <br />' +
							'It was a good day for sure. The beer was actually not so good, but beer is still beer so i was happy for sure.',
		createdAt: new Date('2019-03-05T23:00:00'),
		hashtags:['beer-and-suit','baltika7'],
   		author: 'Иванов Иван',
   		photoLink: 'images/me.jpg',
   		rating:100,
   	},
	{
		id: '2',
		description: 'Hey guys, here is my invention on how to use properly a can of beer. Make a hole with a knife,' +
		' chug the beer and with simple moves with your knife you can make a good dish to make your "Rolton" there. Use this lifehack and share this idea with your friends!',
		createdAt: new Date('2019-03-05T00:00'),
		hashtags:['lifehack','baltika9'],
		author: 'Petya Petrov',
		photoLink: 'images/baltika9.jpg',
		rating:210,
	},
	{
		id: '3',
		description: "Love is a great feeling, but only if it's mutual",
		createdAt: new Date('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'Petya Petrov',
		photoLink: 'images/loveis.jpg',
		rating:1298,
	},
	{
		id: '4',
		description: 'Hey guys, look at me and my wife flexing this sunday at our vilage house!',
		createdAt: new Date('2019-03-05T00:00'),
		hashtags:[],
		author: 'Petya Petrov',
		photoLink: 'images/flex.jpg',
		rating:268,
	},
	{
		id: '5',
		description: 'Just me sitting so hadsome drinking beer.',
		createdAt: new Date('2019-03-05T00:00'),
		hashtags:['beer-and-suit','baltika7'],
		author: 'Petya Petrov',
		photoLink: 'images/baltika7.jpg',
		rating:1979,
	},
	{
		id: '6',
		description: 'Math problems',
		createdAt: new Date('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'Petya Petrov',
		photoLink: 'images/math.jpg',
		rating:918,
	},
	{
		id: '7',
		description: 'Igor Nikolaev drinking for love',
		createdAt: new Date('2019-03-05T00:00'),
		hashtags:[],
		author: 'Petya Petrov',
		photoLink: 'images/party.jpg',
		rating:827,
	},
	{
		id: '8',
		description: 'very nice billboard',
		createdAt: new Date ('2019-03-10T00:00'),
		hashtags:['lifehack'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/PIVO.jpg',
		rating: 1981,
	},
	{
		id: '9',
		description: ' Taking selfi before a great party with my pals',
		createdAt: new Date ('2019-03-05T00:00'),
		hashtags:['beer-and-suit'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/selfi.jpg',
		rating:1778,
	},
	{
		id: '10',
		description: 'Just a cool guy enjoying the sunset ',
		createdAt: new Date ('2019-03-10T00:00'),
		hashtags:['meme','baltika3'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/sunset.jpg',
		rating:1899
	},
	{
		id: '11',
		description: 'Just a cool billboard',
		createdAt: new Date ('2019-03-10T00:00'),
		hashtags:['lifehack'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/billboard2.jpg',
		rating:18,
	},
	{
		id: '12',
		description: 'run for your life...',
		createdAt: new Date ('2019-03-10T00:00'),
		hashtags:['meme'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/running.jpg',
		rating:19812,
	},
	{
		id: '13',
		description: 'Guestion of the eternity',
		createdAt: new Date ('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/skekspire.jpg',
		rating:1092,
	},
	{
		id: '14',
		description: 'My totemic animal',
		createdAt: new Date ('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/sqrl.jpg',
		rating:1902,
	},
	{
		id: '15',
		description: 'Fitness',
		createdAt: new Date ('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/fitness.png',
		rating:1981,
	},
	{
		id: '16',
		description: 'the second another*',
		createdAt: new Date ('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/another.jpg',
		rating:747,
	},
	{
		id: '17',
		description: 'Great result',
		createdAt: new Date ('2019-03-05T00:00'),
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/holdmybeer.jpg',
		rating:918,
	},
	{
		id: '18',
		description: 'the nightmare of the party',
		createdAt: new Date ('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/lastmanstanding.jpg',
		rating:356,
	},
	{
		id: '19',
		description: 'When you have too much to do for UP',
		createdAt: new Date ('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/sad.jpg',
		rating:12386,
	},
	{
		id: '20',
		description: 'the last means the worst',
		createdAt: new Date ('2019-03-05T00:00'),
		hashtags:['meme'],
		author: 'WhatIslove BabyDontHurtovich',
		photoLink: 'images/nightmare.jpg',
		rating:166,
	},
]